# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarim.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(618, 472)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_sayi1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sayi1.setGeometry(QtCore.QRect(50, 60, 51, 31))
        self.lbl_sayi1.setObjectName("lbl_sayi1")
        self.lbl_sayi2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sayi2.setGeometry(QtCore.QRect(50, 110, 51, 31))
        self.lbl_sayi2.setObjectName("lbl_sayi2")
        self.txt_sayi1 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sayi1.setGeometry(QtCore.QRect(100, 50, 221, 41))
        self.txt_sayi1.setObjectName("txt_sayi1")
        self.txt_sayi2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sayi2.setGeometry(QtCore.QRect(100, 100, 221, 41))
        self.txt_sayi2.setObjectName("txt_sayi2")
        self.btn_topla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_topla.setGeometry(QtCore.QRect(40, 250, 81, 31))
        self.btn_topla.setObjectName("btn_topla")
        self.btn_cikar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikar.setGeometry(QtCore.QRect(170, 250, 81, 31))
        self.btn_cikar.setObjectName("btn_cikar")
        self.btn_carp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_carp.setGeometry(QtCore.QRect(290, 250, 81, 31))
        self.btn_carp.setObjectName("btn_carp")
        self.btn_bolme = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bolme.setGeometry(QtCore.QRect(400, 250, 81, 31))
        self.btn_bolme.setObjectName("btn_bolme")
        self.lbl_sonuc = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sonuc.setGeometry(QtCore.QRect(90, 320, 261, 31))
        self.lbl_sonuc.setObjectName("lbl_sonuc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 618, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_sayi1.setText(_translate("MainWindow", "Sayı 1 : "))
        self.lbl_sayi2.setText(_translate("MainWindow", "Sayi 2 :"))
        self.btn_topla.setText(_translate("MainWindow", "Toplama"))
        self.btn_cikar.setText(_translate("MainWindow", "Çıkarma"))
        self.btn_carp.setText(_translate("MainWindow", "Çarpma"))
        self.btn_bolme.setText(_translate("MainWindow", "Bölme"))
        self.lbl_sonuc.setText(_translate("MainWindow", "Sonuc: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
